CREATE TABLE SiswaRiwayat( 
    SiswaId INT NOT NULL DEFAULT(0),
    GolDarah VARCHAR(5) NOT NULL DEFAULT(0),
    RiwayatPenyakit VARCHAR(30) NOT NULL DEFAULT(0),
    KelainanJasmani VARCHAR(30) NOT NULL DEFAULT(0),
    TinggiBdn INT NOT NULL DEFAULT(0),
    BeratBdn INT NOT NULL DEFAULT(0),

    LulusanDr VARCHAR(20) NOT NULL DEFAULT(0),
    TglIjazah DATETIME NOT NULL DEFAULT('3000-01-01'),
    NoIjazah VARCHAR(20) NOT NULL DEFAULT(0),
    LamaBljr VARCHAR(20) NOT NULL DEFAULT(0),

    PindahanDr VARCHAR(20) NOT NULL DEFAULT(0),
    AlasanPindah VARCHAR(100) NOT NULL DEFAULT(0),

    DiterimaTingkat VARCHAR(10) NOT NULL DEFAULT(0),
    KompKeahlian VARCHAR(20) NOT NULL DEFAULT(0),
    TglDiterima DATETIME NOT NULL DEFAULT('3000-01-01'),

    Kesenian VARCHAR(30) NOT NULL DEFAULT(0),
    Olahraga VARCHAR(30) NOT NULL DEFAULT(0),
    Organisasi VARCHAR(30) NOT NULL DEFAULT(0),
    Hobi VARCHAR(30) NOT NULL DEFAULT(0),
    CitaCita VARCHAR(20) NOT NULL DEFAULT(0),
    TglTinggalSekolah DATETIME NOT NULL DEFAULT('3000-01-01'),
    AlasanTinggal VARCHAR(100) NOT NULL DEFAULT(0),
    AkhirTamatBljr DATETIME NOT NULL DEFAULT('3000-01-01'),
    AkhirNoIjazah VARCHAR(20)NOT NULL DEFAULT(0),
    
    CONSTRAINT PK_SiswaRiwayat PRIMARY KEY CLUSTERED(SiswaId)
)
GO